### ISSUE TITLE
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by bomtorazek** [hfslyc/AdvSemiSeg#45]
I got RuntimeError: CUDNN_STATUS_EXECUTION_FAILED when executing evaluation_voc.py

My conda list is below
python                    2.7.17               h9bab390_0  
python-dateutil           2.8.1                      py_0  
pytorch                   0.4.0            py27hdf912b8_0  
cudatoolkit               9.0                  h13b8566_0  
cudnn                     7.6.4                 cuda9.0_0  

The weird thing is that train.py, which uses the same modules, works well with the same environment.

P.S. If the version of pytorch is upper than 0.4, the following adjustment is required.
    with torch.no_grad():  
        for index, batch in enumerate(testloader):
            if index % 100 == 0:
                print('%d processd'%(index))
            image, label, size, name = batch
            size = size[0].numpy()
            output = model(image.cuda(args.gpu))
            output = interp(output).cpu().data[0].numpy()

**Comment by bomtorazek** [comment]
It was the CUDNN problem regarding GPU (RTX 2080 Ti)

I solved it by moving to the upper version of CUDNN.

python                    2.7.17               h9bab390_0  
python-dateutil           2.8.1                      py_0  
pytorch                   1.0.1           cuda100py27he554f03_0 
cudatoolkit               10.0.130                      0  
cudnn                     7.6.4                cuda10.0_0  

Btw, I still don't know train.py works well with the previous settings, but evaluation does not.
